const TokenEventResult = {
	SUCCESSFUL: 0,
	FAIL_INSUFFICIENT_BALANCE: 1,
	DATA_TOO_LONG: 2,
	INVALID_TOKEN_ID: 3,
	TOKEN_NOT_SUPPORTED: 4,
	INSUFFICIENT_LOCKED_AMOUNT: 5,
	RECOVER_FAIL_INVALID_INPUTS: 6,
	RECOVER_FAIL_INSUFFICIENT_ESCROW: 7,
	MINT_FAIL_NON_NATIVE_TOKEN: 8,
	MINT_FAIL_TOTAL_SUPPLY_TOO_BIG: 9,
	MINT_FAIL_TOKEN_NOT_INITIALIZED: 10,
	TOKEN_ID_NOT_AVAILABLE: 11,
	TOKEN_ID_NOT_NATIVE: 12,
	INSUFFICIENT_ESCROW_BALANCE: 13,
	INVALID_RECEIVING_CHAIN: 14,
};

module.exports = { TokenEventResult };
