version: '3'
services:
  klayr-core:
    image: klayr/core:4.1.1
    platform: linux/amd64
    volumes:
      - ./snapshots/:/tmp/snapshots
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - '7887:7887'
    restart: always
    entrypoint: ['sh', '/entrypoint.sh']
    environment:
      - KLAYR_API_PUBLIC=true
